// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de": &dictionary{index: deIndex, data: deData},
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	" (Overtime)": 8,
	" (Own goal)": 9,
	" (Penalty)":  7,
	"# Game <font color=\"%[5]s\">%[1]s</font> vs. <font color=\"%[6]s\">%[2]s</font> ***(<font color=\"%[5]s\">%[3]d</font>:<font color=\"%[6]s\">%[4]d</font>)***\n\n": 0,
	"## **Goals**\n\n": 4,
	"## Results\n\n":   11,
	"* %[1]s - <font color=\"%[2]s\">%[4]d</font>:<font color=\"%[3]s\">%[5]d</font> - Goal for %[6]s by %[7]s%[8]s\n": 10,
	"* **Halftime result":            12,
	"* **Result":                     17,
	"* **Result after 90 minutes":    13,
	"* **Result after extended Time": 14,
	"* **Result after overtime":      15,
	"* **Result after penalty shots": 16,
	"**Game Completed** - ":          1,
	"*Game began %s*\n\n\n\n":        2,
	"*Game beginning %s*\n\n\n\n":    3,
	"*No goals yet*\n\n":             5,
	"Data provided by [OpenLigaDB.de](https://www.openligadb.de) | [Sourcecode](https://github.com/Unkn0wnCat/matrix-soccerbot)": 18,
	"matrix-soccerbot has started.": 19,
	"unknown":                       6,
}

var deIndex = []uint32{ // 21 elements
	0x00000000, 0x0000009f, 0x000000b8, 0x000000d5,
	0x000000f3, 0x00000105, 0x0000011d, 0x00000127,
	0x0000013a, 0x0000014f, 0x0000015f, 0x000001d2,
	0x000001e6, 0x000001f8, 0x00000212, 0x0000022f,
	0x0000024c, 0x0000026d, 0x0000027a, 0x000002fe,
	0x000002fe,
} // Size: 108 bytes

const deData string = "" + // Size: 766 bytes
	"\x04\x00\x02\x0a\x0a\x98\x01\x02# Spiel <font color=\x22%[5]s\x22>%[1]s<" +
	"/font> vs. <font color=\x22%[6]s\x22>%[2]s</font> ***(<font color=\x22%[" +
	"5]s\x22>%[3]d</font>:<font color=\x22%[6]s\x22>%[4]d</font>)***\x04\x00" +
	"\x01 \x14\x02**Spiel beendet** -\x04\x00\x04\x0a\x0a\x0a\x0a\x15\x02*Spi" +
	"el begann %[1]s*\x04\x00\x04\x0a\x0a\x0a\x0a\x16\x02*Spiel beginnt %[1]s" +
	"*\x04\x00\x02\x0a\x0a\x0c\x02## **Tore**\x04\x00\x02\x0a\x0a\x12\x02*Noc" +
	"h keine Tore*\x02unbekannt\x04\x01 \x00\x0e\x02(Strafschuss)\x04\x01 " +
	"\x00\x10\x02(Nachspielzeit)\x04\x01 \x00\x0b\x02(Eigentor)\x04\x00\x01" +
	"\x0an\x02* %[1]s - <font color=\x22%[2]s\x22>%[4]d</font>:<font color=" +
	"\x22%[3]s\x22>%[5]d</font> - Tor für %[6]s durch %[7]s%[8]s\x04\x00\x02" +
	"\x0a\x0a\x0e\x02## Ergebnisse\x02* **Halbzeitstand\x02* **Stand nach 90 " +
	"Minuten\x02* **Stand nach Nachspielzeit\x02* **Stand nach Verlängerung" +
	"\x02* **Stand nach Elfmeterschießen\x02* **Ergebnis\x02Daten bereitgeste" +
	"llt durch [OpenLigaDB.de](https://www.openligadb.de) | [Quellcode](https" +
	"://github.com/Unkn0wnCat/matrix-soccerbot)"

var enIndex = []uint32{ // 21 elements
	0x00000000, 0x0000009e, 0x000000b8, 0x000000d3,
	0x000000f2, 0x00000105, 0x0000011a, 0x00000122,
	0x00000131, 0x00000141, 0x00000151, 0x000001c1,
	0x000001d2, 0x000001e6, 0x00000202, 0x00000221,
	0x0000023b, 0x0000025a, 0x00000265, 0x000002e0,
	0x000002fe,
} // Size: 108 bytes

const enData string = "" + // Size: 766 bytes
	"\x04\x00\x02\x0a\x0a\x97\x01\x02# Game <font color=\x22%[5]s\x22>%[1]s</" +
	"font> vs. <font color=\x22%[6]s\x22>%[2]s</font> ***(<font color=\x22%[5" +
	"]s\x22>%[3]d</font>:<font color=\x22%[6]s\x22>%[4]d</font>)***\x04\x00" +
	"\x01 \x15\x02**Game Completed** -\x04\x00\x04\x0a\x0a\x0a\x0a\x13\x02*Ga" +
	"me began %[1]s*\x04\x00\x04\x0a\x0a\x0a\x0a\x17\x02*Game beginning %[1]s" +
	"*\x04\x00\x02\x0a\x0a\x0d\x02## **Goals**\x04\x00\x02\x0a\x0a\x0f\x02*No" +
	" goals yet*\x02unknown\x04\x01 \x00\x0a\x02(Penalty)\x04\x01 \x00\x0b" +
	"\x02(Overtime)\x04\x01 \x00\x0b\x02(Own goal)\x04\x00\x01\x0ak\x02* %[1]" +
	"s - <font color=\x22%[2]s\x22>%[4]d</font>:<font color=\x22%[3]s\x22>%[5" +
	"]d</font> - Goal for %[6]s by %[7]s%[8]s\x04\x00\x02\x0a\x0a\x0b\x02## R" +
	"esults\x02* **Halftime result\x02* **Result after 90 minutes\x02* **Resu" +
	"lt after extended Time\x02* **Result after overtime\x02* **Result after " +
	"penalty shots\x02* **Result\x02Data provided by [OpenLigaDB.de](https://" +
	"www.openligadb.de) | [Sourcecode](https://github.com/Unkn0wnCat/matrix-s" +
	"occerbot)\x02matrix-soccerbot has started."

	// Total table size 1748 bytes (1KiB); checksum: 2FF62235
